// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdtEEfZlLB0y6l6TLZmflJWNk3EjuDzbY',
    appId: '1:1095906260558:web:aba10fd98c12af7ba2b51f',
    messagingSenderId: '1095906260558',
    projectId: 'dropper-c7adc',
    authDomain: 'dropper-c7adc.firebaseapp.com',
    storageBucket: 'dropper-c7adc.appspot.com',
    measurementId: 'G-6ECL23SNE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUUWieWD78wTHfm4r3qPRiE4U6JIn7zVM',
    appId: '1:1095906260558:android:8cb4ce44454c5cd2a2b51f',
    messagingSenderId: '1095906260558',
    projectId: 'dropper-c7adc',
    storageBucket: 'dropper-c7adc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoL8yCXlUGvnXQ_rRKZfMaYuJG-S_OqoY',
    appId: '1:1095906260558:ios:a3f29e84799816e3a2b51f',
    messagingSenderId: '1095906260558',
    projectId: 'dropper-c7adc',
    storageBucket: 'dropper-c7adc.appspot.com',
    iosClientId:
        '1095906260558-hh9t3o8v1upqjdoho8dogn629jq0st3n.apps.googleusercontent.com',
    iosBundleId: 'com.example.ebay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoL8yCXlUGvnXQ_rRKZfMaYuJG-S_OqoY',
    appId: '1:1095906260558:ios:a3f29e84799816e3a2b51f',
    messagingSenderId: '1095906260558',
    projectId: 'dropper-c7adc',
    storageBucket: 'dropper-c7adc.appspot.com',
    iosClientId:
        '1095906260558-hh9t3o8v1upqjdoho8dogn629jq0st3n.apps.googleusercontent.com',
    iosBundleId: 'com.example.ebay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdtEEfZlLB0y6l6TLZmflJWNk3EjuDzbY',
    appId: '1:1095906260558:web:ad5e86371a8e2a09a2b51f',
    messagingSenderId: '1095906260558',
    projectId: 'dropper-c7adc',
    authDomain: 'dropper-c7adc.firebaseapp.com',
    storageBucket: 'dropper-c7adc.appspot.com',
    measurementId: 'G-QQ3PWR9E0T',
  );
}
